- documentation/content/docs/tools.md
- js/examples/main.js
- js/package.json
- js/src/ProcessLauncher/index.js
- js/src/SmartConnect/index.js
- js/src/WebsocketConnection/index.js
- python/requirements.txt
- python/src/wslink/websocket.py
Cleanup comments and example in js - with commented test for
WebsocketConnection.destroy()
Chain .destroy() calls, so default .destroy() is also called.
Remove extra "Starting factory" message which isn't needed.
Python:
py2.7 pypiwin32 has different version - use any version in requirements.txt
Add back super().__init__() call, to fix exception when using current Autobahn -
one of the parent classes has an __init__() which needs to be called.
Old autobahn from VTK still works because multiple inheritance from 'object'
ensures that the super() call works on py2.
> JS cleanup, destroy chaining, py2 requirements, autobahn fix

- js/src/CompositeClosureHelper/index.js
- js/src/WebsocketConnection/session.js
- js/test/main.js
- python/examples/myProtocol.py
Support a client doing 'return self.addAttachment(buffer)' from
an RPC method. JS must check if a result is a string representing
the binary attachment. Add a test.
CC @jourdain
> fix(session): support RPC with just a binary attachment result.

- python/requirements-dev.txt
- python/setup.py
- python/src/wslink/__init__.py
What do you think of adding this dependency as an extra?  Then other projects could get that installed ala:
```
pip install wslink[security]
```
See the pip [docs](https://pip.pypa.io/en/stable/reference/pip_install/#examples) for more details.  And according to [PEP508](https://www.python.org/dev/peps/pep-0508/#extras), they could also list it in their `requirements.txt` in a similar way:
```
wslink[security]
```
@aron-helser @jourdain Does this seem reasonable to you?
> fix(deps): Add extras_require for service_identity

- python/src/wslink/__init__.py
- python/src/wslink/launcher.py
Add 'santize' key to the launcher config, so potential values
provided by the client can be compared to known values before
executing them as a process. Verify against a list or regexp.
@jourdain what do you think? Should I leave in the log.warning()?
> fix(launcher): santize potential command lines

- python/src/tests/test-wslink.conf
- python/src/wslink/__init__.py
- python/src/wslink/launcher.py
Allow JS/C++ comments in launcher config. Add comments and sample
of sanitize config. Add test config used to tests/ dir.
CC @jourdain
> fix(launcher.py): Don't enforce begin/end marks in sanitize regexp

- js/src/WebsocketConnection/session.js
We noticed a memory leak working with https://kitware.github.io/paraviewweb/examples/RemoteRenderer.html#Using-ParaView-as-server. In the web-browser, there are lots of strings, that are not freed. These strings contain the transmitted image data. Therefore each time a new picture is rendered, the needed memory rises (see attached screenshot).
We identified the inFlightRpc object as the culprit. This stores all RPCs, and they are never deleted. A possible solution, that did not cause any errors for us, was deleting them after they are processed.
> Possible Memory Leak: session.inFlightRpc keeps all RPCs

- js/package.json
- js/src/SmartConnect/api.md
- js/src/SmartConnect/index.js
- js/src/WebsocketConnection/index.js
The close event contains contents of the close frame sent by the server. The close frame is used by the server to inform of the connection setup problem.
> Forward the websocket close event to application callbacks

- python/src/wslink/__init__.py
This PR allows applications to schedule tasks (via `schedule_callback` and `schedule_coroutine`) before the server is started.  Previously, attempting to do this raised a RuntimeError due to no event loop running.
> fix(scheduling): Support scheduling tasks before server starts

- python/src/wslink/backends/aiohttp/__init__.py
When using vtk.js remoteView together with wslink and vtkWeb we run into websocket timeouts whenever a user doesn't interact for more than 60s. While not exactly sure who is responsible for interrupting the connection (apache, wslink) another side-effect of those interrupted sessions is that wslink does not shutdown these correctly.
Looking at the code wslink async awaits on new messages but in case of (forced) connection drop it basically hangs forever waiting for messages on a dead client.
While it would be possible to add ws ping to our client code it would only partially solve the issue of leaked sessions, it would keep connections alive but any network interruption would still lead to the issue described.
So the imho better approach would be to use the built in 'heartbeat' …
> enable heartbeat to shutdown clients on network interrupt

- python/src/wslink/backends/aiohttp/__init__.py
- python/src/wslink/websocket.py
onConnect(request, client_id) -> None
onClose(client_id) -> None
They are called when a websocket connection is established or closed.  Arg
request is the aiohttp HTTP request header. client_id is an opaque string that
identifies the connection.  onC
Our use case is use an HTTP cookie in the request header to authenticate the
request.
A clear and concise description of what the problem was and how this pull request solves it.
fix #ISSUE_NUMBER
> Add onConnect on onClose methods to ServerProtocol and LinkProtocol

- python/src/wslink/backends/aiohttp/__init__.py
Downgrade the level of wslink startup message from critical to info.
A clear and concise description of what the problem was and how this pull request solves it.
fix #ISSUE_NUMBER
> fix(python): downgrade the startup log message

- js/src/SmartConnect/index.d.ts
- js/src/WebsocketConnection/index.d.ts
Add typescript definitions for SmartConnect and WebsocketConnection.  They cover
most, not all, of the commonly used types.
A clear and concise description of what the problem was and how this pull request solves it.
fix #ISSUE_NUMBER
> doc(js): Add type definitions

- js/src/SmartConnect/index.d.ts
This change only modifies typescript definitions. There is no change to the functionality.
> fix(js): Add more type annotations

- js/src/WebsocketConnection/index.d.ts
subscribe now returns a pair of (promise, unsubscribe) instead of subscriber ID.
> fix(ts): update the type definitions for subscribe

- js/src/WebsocketConnection/index.d.ts
Simply add a missing typescript definition.
> doc(ts): WebsocketSession addAttachment definition

- python/src/wslink/backends/aiohttp/__init__.py
- python/src/wslink/server.py
Allow to pass a value of 0 to timeout for wslink server, to disable the automatic shutdown.
fix #97
> feat(timeout): allow server without shutdown timeout

- js/src/SmartConnect/index.js
The value of window.location.protocol ends with ':'.
I didn't know how to rename properly, so I had to start over.
Thanks for the advice.
> fix(js): Properly handle protocol mapping

- js/src/WebsocketConnection/index.d.ts
Correct typescript signature of the `WebsocketSession.call` method,
adding the accepted optional `kwargs` parameter.
> docs(types): add optional kwargs parameter to WebsocketSession.call signature

- python/requirements.txt
- python/setup.py
Hi,
I originally opened this vtk issue - https://gitlab.kitware.com/vtk/vtk/-/issues/18591
Essentially, installing vtk (and as a result, wslink) with `pip install --pre` leads to https://github.com/aio-libs/aiohttp/issues/6799.
This goes around the problem by avoid the 4.x series of aiohttp, which may introduce breaking changes and is still not stable.
> MAINT: Avoid newer, breaking versions of aiohttp

- python/setup.py
- python/src/wslink/backends/aiohttp/__init__.py
- python/src/wslink/server.py
- python/src/wslink/ssl_context.py
On some cloud platforms (here AWS), we need the ssl/wss protocol to be used. 
aiohttp is able to handle such connexion but it was not accessible from the wslink API.
We also added the ability to create a temporary certificate.
fix #112
> Support SSL context 

- python/src/wslink/backends/aiohttp/__init__.py
Check with `_valid_token` is imperfect as it is a global flag, and is enforced only for incoming messages. Thus it's possible for a client to connect silently to the socket, never send a handshake. As long as there's at least one authenticated client, those unauthenticated clients will currently receive messages and attachments.
Store the list of authenticated clients in a `authentified_client_ids` set.
Use it for incoming message, and only broadcast to websockets who have passed authentication.
> fix(security): publish messages only to authenticated clients

- python/src/wslink/server.py
- Handle backend exit exception instead of letting it propagate to application level. The `aiohttp` backend raises `GracefulExit` a subclass of `SystemExit`. This code assumes any other backend would similarly raise a `SystemExit` derived exception.
- To achieve the above, the event loop must not be closed. Besides, calling code may want to schedule application clean up after server connection is closed.
> fix(gracefulexit): handle server exit for exec_mode=main

- js/src/SmartConnect/index.js
- js/src/WebsocketConnection/index.js
> fix RPC call application.exit.later unsuccessful: connection not open

- python/src/wslink/backends/aiohttp/__init__.py
- python/src/wslink/backends/aiohttp/launcher.py
- python/src/wslink/backends/aiohttp/relay.py
- python/src/wslink/backends/generic/core.py
- python/src/wslink/launcher.py
- python/src/wslink/protocol.py
- python/src/wslink/websocket.py
Implements properly scoped logging. Prior to these changes, `wslink` was hijacking the root logger for its logging and setting global configurations that would conflict with settings for other packages or by users.
fix #151
> fix(logging): implement scoped logging

- js/package-lock.json
- js/package.json
- js/src/WebsocketConnection/chunking.js
- js/src/WebsocketConnection/chunking.ts
- js/src/WebsocketConnection/session.js
- python/requirements.txt
- python/setup.py
- python/src/wslink/chunking.py
- python/src/wslink/protocol.py
- python/src/wslink/publish.py
- Use msgpack for serialization of the messages between server and client
- slightly reduced message size
- binary values can directly be in the object serialized/deserialized (no need to use previous attachment mechanism)
- Chunk messages
- avoids the websocket connection to close unexpectedly when a large message is exchanged
- use existing environmental variable `WSLINK_MAX_MSG_SIZE` to determine the chunk size
> Rework the way messages are exchanged between server and client (msgpack + chunking)

- python/src/wslink/chunking.py
When sending a JWT token along with a message, this size ends up too small and results in a ValueError. This PR increases max_message_size to 3000 to accommodate.
fix #157
> fix(unchunker): initial allowed message size to env var

- python/src/wslink/backends/aiohttp/__init__.py
- Fix #159 
If adding the `__future__`  import is the way you want to go, here it is. Feel free to close if you want to go another direction.
A simple test importing `from wslink.backends import aiohttp` confirms the fix.
> fix: fix type hints for python < 3.10 on aiohttp backend

- python/src/wslink/backends/generic/core.py
- python/src/wslink/backends/jupyter/core.py
- python/src/wslink/emitter.py
- python/src/wslink/protocol.py
- python/src/wslink/websocket.py
Internal messages within the wslink protocol are published on an object that clients can subscribe to.
Example usage in trame:
```python
def handle_errors(self, message: str):
pass
def handle_exceptions(self, e: Exception):
pass
server.protocol.log_emitter.add_event_listener("error", handle_errors)
server.protocol.log_emitter.add_event_listener("exception", handle_exceptions)
```
> feat(protocol): log internal events through an object that can be subscribed to
